name: scrape bfm

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  scrape_bfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          #pip install minet==0.56.2
          pip install git+https://github.com/paulgirard/minet.git@acquire_guest_token_by_api
      - name: scrape @BFMTV tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@BFMTV since:2021-09-01" > bfmtv-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > bfmtv-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @bfmtv
