name: scrape cnews

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  scrape_cnews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.56.2
      - name: scrape @cnews tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@CNEWS since:2021-09-01" > cnews-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > cnews-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @cnews
