name: scrape tweets

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scrape_cnews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.55.2
      - name: scrape @cnews tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@CNEWS since:2021-09-01" > cnews-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > cnews-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @cnews
  scrape_bfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.55.2
      - name: scrape @BFMTV tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@BFMTV since:2021-09-01" > bfmtv-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > bfmtv-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @bfmtv
  scrape_franceinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.55.2
      - name: scrape @franceinfo tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@franceinfo since:2021-09-01" > franceinfo-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > franceinfo-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @franceinfo
  scrape_mediapart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.55.2
      - name: scrape @mediapart tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@Mediapart since:2021-09-01" > mediapart-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > franceinfo-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @Mediapart
