name: scrape tweets

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/3 * * * *'

jobs:
  scrape_cnews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.52.6
      - name: scrape @cnews tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@CNEWS" --limit 10000 > cnews-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > cnews-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @cnews
  scrape_bfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install minet
        run: |
          python -m pip install --upgrade pip
          pip install minet==0.52.6
      - name: scrape @BFMTV tweets
        shell: bash
        run: |
          minet tw scrape tweets "from:@BFMTV" --limit 10000 > bfmtv-tweets.csv
          #minet tw scrape tweets "cnews" --limit 10000 > bfmtv-tweets.csv
      - name: commit
        uses: ./.github/actions/commit
        with:
          message: lol @bfmtv
